app = "hot-date"
primary_region = "syd"

[build]
  image = "ghcr.io/lewinfox/hot-date:latest"

[env]
  NODE_ENV = "production"
  DATABASE_PATH = "/data/hot-date.db"

[[mounts]]
  source = "hot_data_data"
  destination = "/data"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop" # scale to zero
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
